# Words per sound, taken from "PHONICS GROUP 1-7.docx".
# Group 1 gives one shared list for s, a, t and i.
# Group 6's two "th" sets are matched by sound, not by position: her document
# lists the voiced set (this/that) first, the app lists unvoiced (thin) first.
WORDS = {
    "s": ["at", "it", "sit", "its"],
    "a": ["at", "it", "sit", "its"],
    "t": ["at", "it", "sit", "its"],
    "i": ["at", "it", "sit", "its"],
    "p": ["pat", "tap", "tip", "sip", "pass"],
    "n": ["nap", "ant", "pan", "pin", "tin"],
    "c_k": ["kiss", "kick", "sick", "pick", "kit", "car", "cat", "kite"],
    "e": ["pet", "pen", "ten", "test", "neck"],
    "h": ["hen", "hat", "hip", "hit", "had"],
    "r": ["rap", "rip", "ran", "rest", "rack"],
    "m": ["man", "map", "ham", "him", "miss"],
    "d": ["dad", "sad", "red", "mad", "kid"],
    "g": ["gas", "pig", "egg", "rag", "tag"],
    "o": ["top", "hot", "hop", "dot", "sock"],
    "u": ["nut", "sun", "cup", "run", "duck"],
    "l": ["lap", "legs", "lips", "lick", "milk"],
    "f": ["fun", "fan", "left", "lift", "gift"],
    "b": ["bad", "bed", "bag", "bug", "rub"],
    "ai": ["rain", "sail", "pain", "nail", "paint"],
    "j": ["jet", "jam", "job", "jump", "jug"],
    "oa": ["boat", "goat", "soap", "road", "goal"],
    "ie": ["pie", "tie", "lie", "die", "lied"],
    "ee": ["see", "feet", "beef", "sleep", "green"],
    "or": ["horn", "pork", "fork", "corn", "sort"],
    "z": ["zip", "buzz", "zap", "fizz", "zigzag"],
    "w": ["week", "went", "wait", "west", "wind"],
    "ng": ["sing", "wings", "ring", "king", "hang"],
    "v": ["vest", "vent", "vail", "van", "vet"],
    "oo_short": ["good", "foot", "look", "cook", "book"],
    "oo_long": ["zoo", "food", "room", "pool", "moon"],
    "y": ["yes", "yap", "yak", "yuck", "yum"],
    "x": ["six", "box", "next", "fix", "mix"],
    "ch": ["chin", "chat", "check", "chest", "lunch"],
    "sh": ["fish", "shop", "shut", "short", "ship"],
    "th_voiced": ["this", "that", "then", "them", "than"],
    "th_unvoiced": ["thin", "thing", "teeth", "three", "thick"],
    "qu": ["quiz", "quick", "queen", "quit", "quack"],
    "ou": ["loud", "mouth", "sound", "shout", "round"],
    "oi": ["oil", "boil", "point", "join", "soil"],
    "ue": ["due", "glue", "blue", "true", "rescue"],
    "er": ["her", "sister", "silver", "litter", "winner"],
    "ar": ["farm", "card", "park", "smart", "start"],
}
